### PR TITLE
Seeding and "Unseeding" the Database

### PR DESCRIPTION
**Pull request by andrewclarkson**
I added two `manage.py` commands `seed` and `unseed`

I figure this might help during development, as this gives us some demo data to play with.

### CODE REVIEW

**Comment by rfinz** [comment]
Hey Andrew, did you actually run those with the data you found? I was getting

```
SyntaxError: Non-ASCII character '\xe2' in file /home/prometheoid/Projects/StacksPy/rfinz/stacks/stacks/library/management/commands/seed.py on line 17
```

It's just because there's a couple dashes in the book descriptions that are unicode en-dashes or something, but apparently my system didn't like that the file had mixed encoding. 

If it succeeded locally maybe there's some difference between our systems?

**Comment by andrewclarkson** [comment]
Yeah, I did...

I guess I probably copied a Unicode character from the Amazon descriptions. My system never gave me any grief, but there's also no reason for that to be in there.

**Comment by rfinz** [comment]
It was a few single quotes and en-dashes. I eliminated them in my copy, but it could also be solved with an encoding string at the top of the file (from here: http://www.python.org/dev/peps/pep-0263/). Either way, I guess.

I wonder whether if it's how github stores the files? I know vim handles unicode encoded files automatically, so maybe they got changed back during the upload or something? I really don't know.

**Comment by andrewclarkson** [comment]
Good deal. I'll open an issue, kill the characters (because they serve no purpose), and then PR.

I noticed also that my defaults are all utf-8. Huh...

``` python
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.getfilesystemencoding()
'utf-8'
```

**Comment by rfinz** [comment]
Ah see, mine are ascii. Damn you SUSE.

**Pull request merged**
