### PR TITLE
Create testGitHubDocument

### PR DESCRIPTION
**Pull request by exlibris**
Test file for users to test / learn github

Please let me know if this document is received.  It is intended to test the gitHub workflow.  I forked the stacks app, made changes, and am not attempting a pull request.

I am unsure if this model is how we are suppose to be working on this via the "fork pull" model or the "Shared Repository Model" as described here: https://help.github.com/articles/using-pull-requests

### CODE REVIEW

**Comment by maestrofjp** [comment]
Yes, we'll use the fork and pull model.  I think the best step-by-step guide for this is from the Xively-Python package:

https://github.com/xively/xively-python/blob/master/CONTRIBUTING.md#contributing-to-xively-libraries

We should adapt a version of its for Stacks.

**Comment by exlibris** [comment]
Thanks, I will read the guide.  I noticed though that I could directly edit files in the pyMNtos repo, so evidently these models are enforced by convention rather than hard coded rules.

**Comment by rfinz** [comment]
> I noticed though that I could directly edit files in the pyMNtos repo, so evidently these models are enforced by
> convention rather than hard coded rules.

:+1: 

Hard coded rules are present for most open source repositories! 
In the case of the PyMNtos stacks repository, we've all been given write access in order to be able to contribute to the wiki freely. SO, wiki edits are one thing you don't need to submit a pull request for. :)

**Comment by fawcett** [comment]
You have been given great power.  Use it only for good...

**Pull request merged**
